steps:
- id: build-image
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args: ['-c',"docker build -t eu.gcr.io/my-project-72088-1707044232660/test-backend:$SHORT_SHA ./backend/"]

- id: push-image
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/my-project-72088-1707044232660/test-backend:$SHORT_SHA']


- id: deploy-image
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
    - 'run'
    - 'deploy'
    - '--image=eu.gcr.io/my-project-72088-1707044232660/test-backend:$SHORT_SHA'
    - '--region=us-central1'
    - '--allow-unauthenticated'
    - '--cpu=2'
    - '--memory=2Gi'
    - '--cpu-boost'
    - '--timeout=500s'
    - '--platform=managed'
    
#   volumes:
#     - name: 'myvolume'
#       path: '/storage'


# - id: deploy-image
#   name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args: 
#     - 'run'
#     - 'deploy'
#     - '$_GCP_SERVICE_NAME' # Replace with your preferred service name
#     - '--image=eu.gcr.io/my-project-72088-1707044232660/test-backend:$SHORT_SHA'
#     - '--region=us-central1'
#     - '--allow-unauthenticated'
#     - '--cpu=2'
#     - '--memory=2Gi'
#     - '--cpu-boost'
#     - '--timeout=500s'

images: ['eu.gcr.io/my-project-72088-1707044232660/test-backend:$SHORT_SHA']
